services:
  api:
    container_name: api-dev
    command: bash -c "bunx prisma generate && bun start:dev"
    env_file: .env.development
    environment:
      - PORT=${API_PORT}
    depends_on:
      - db
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - "./api/:/app"
    ports:
      - "${API_PORT}:${API_PORT}"
  client:
    container_name: client-dev
    depends_on:
      - api
    command: bun dev
    environment:
      - PORT=${CLIENT_PORT}
    volumes:
      - "./client/:/app"
    build:
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
  db:
    image: postgres
    restart: always
    container_name: db-dev 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
