services:
  api:
    container_name: api-dev
    command: bun start:dev
    env_file: .env.development
    depends_on:
      - db
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - "./api/:/app"
    ports:
      - "8000:8000"
  client:
    container_name: client-dev
    depends_on:
      - api
    command: bun dev
    env_file: .env.development
    volumes:
      - "./client/:/app"
    build:
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    container_name: db-dev 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
